# Generated by Django 4.0.5 on 2022-06-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('period', models.PositiveSmallIntegerField(choices=[(0, 'pontual'), (3, 'trimestral'), (6, 'semestral'), (12, 'anual'), (24, 'a cada 2 anos'), (36, 'a cada 3 anos'), (60, 'a cada 5 anos'), (120, 'a cada 10 anos')], default=0)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.setor')),
            ],
        ),
    ]
