# Generated by Django 4.0.5 on 2022-06-17 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('realizado', models.BooleanField()),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.fornecedor')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.servico')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.setor')),
            ],
        ),
    ]
